import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Terms of Service — ToolNinja",
  description: "ToolNinja terms of service. Free to use for personal and commercial projects. All tools run in your browser with no warranties.",
};

export default function TermsPage() {
  return (
    <div className="px-6 py-12 max-w-2xl mx-auto">
      <Link href="/" className="text-xs text-[#555555] hover:text-[#888888] transition-colors mb-8 inline-block">
        ← Back to tools
      </Link>

      <h1 className="text-2xl font-bold text-[#f5f5f5] mb-2">Terms of Service</h1>
      <p className="text-xs text-[#555555] mb-10">Last updated: May 2026</p>

      <div className="space-y-8 text-sm text-[#888888] leading-relaxed">

        <section>
          <h2 className="text-base font-semibold text-[#d4d4d4] mb-3">1. Acceptance</h2>
          <p>
            By accessing or using ToolNinja (&quot;the Service&quot;), you agree to these Terms of Service.
            If you do not agree, please do not use the Service. These terms apply to all visitors
            and users.
          </p>
        </section>

        <section>
          <h2 className="text-base font-semibold text-[#d4d4d4] mb-3">2. What ToolNinja is</h2>
          <p>
            ToolNinja is a collection of free, browser-based developer utilities. All tool logic
            runs client-side in your browser using JavaScript and standard Web APIs. No account or
            subscription is required. We reserve the right to add, modify, or remove tools at any time.
          </p>
        </section>

        <section>
          <h2 className="text-base font-semibold text-[#d4d4d4] mb-3">3. Permitted use</h2>
          <p className="mb-3">
            You may use ToolNinja for personal and commercial projects, free of charge. You may not:
          </p>
          <ul className="space-y-1.5 list-none">
            {[
              "Attempt to circumvent, disable, or interfere with any security feature of the Service",
              "Use automated means to scrape, mirror, or systematically copy the Service without permission",
              "Use the Service in any way that violates applicable laws or regulations",
              "Represent ToolNinja as your own product or remove attribution",
            ].map((item) => (
              <li key={item} className="flex gap-2">
                <span className="text-[#a855f7] mt-0.5 shrink-0">—</span>
                <span>{item}</span>
              </li>
            ))}
          </ul>
        </section>

        <section>
          <h2 className="text-base font-semibold text-[#d4d4d4] mb-3">4. No warranties</h2>
          <p>
            The Service is provided <strong className="text-[#d4d4d4]">&quot;as is&quot;</strong> and
            <strong className="text-[#d4d4d4]"> &quot;as available&quot;</strong>, without any warranty of
            any kind, express or implied. We do not warrant that the tools are error-free, complete,
            accurate, or fit for any particular purpose. You use them at your own risk.
          </p>
          <p className="mt-3">
            In particular, cryptographic tools such as key generators and encryption utilities are
            provided for educational and convenience purposes. Do not rely solely on any browser-based
            tool for production security-critical operations without independent verification.
          </p>
        </section>

        <section>
          <h2 className="text-base font-semibold text-[#d4d4d4] mb-3">5. Limitation of liability</h2>
          <p>
            To the maximum extent permitted by applicable law, ToolNinja and its operators shall not
            be liable for any indirect, incidental, special, consequential, or punitive damages arising
            from your use of or inability to use the Service, even if advised of the possibility of
            such damages. Our total liability for any claim shall not exceed zero dollars, as the
            Service is provided free of charge.
          </p>
        </section>

        <section>
          <h2 className="text-base font-semibold text-[#d4d4d4] mb-3">6. Intellectual property</h2>
          <p>
            The ToolNinja name, logo, and site design are owned by the operator. The underlying
            open-source libraries used by ToolNinja are subject to their respective licenses.
            Tool output generated by the Service (formatted code, converted data, etc.) is yours
            to use without restriction.
          </p>
        </section>

        <section>
          <h2 className="text-base font-semibold text-[#d4d4d4] mb-3">7. External links</h2>
          <p>
            The Service may contain links to external websites. We are not responsible for the
            content or privacy practices of those sites.
          </p>
        </section>

        <section>
          <h2 className="text-base font-semibold text-[#d4d4d4] mb-3">8. Changes to these terms</h2>
          <p>
            We may update these terms at any time. Changes take effect when posted. Continued use
            of the Service after an update constitutes acceptance of the revised terms.
          </p>
        </section>

        <section>
          <h2 className="text-base font-semibold text-[#d4d4d4] mb-3">9. Governing law</h2>
          <p>
            These terms are governed by and construed in accordance with applicable law. Any disputes
            shall be resolved in the courts of the operator&apos;s jurisdiction.
          </p>
        </section>

      </div>

      <div className="mt-12 pt-6 border-t border-[#1a1a1a] flex gap-4 text-xs text-[#444444]">
        <Link href="/privacy" className="hover:text-[#666666] transition-colors">Privacy Policy</Link>
        <span>·</span>
        <Link href="/" className="hover:text-[#666666] transition-colors">Back to tools</Link>
      </div>
    </div>
  );
}
