export type GitCategory =
  | "Setup"
  | "Branches"
  | "Staging"
  | "Commits"
  | "Remote"
  | "Undo"
  | "History"
  | "Tags"
  | "Stash"
  | "Advanced";

export interface GitCommand {
  id: string;
  name: string;
  description: string;
  command: string;
  tags: string[];
  category: GitCategory;
  warning?: string;
}

export const gitCategories: GitCategory[] = [
  "Setup",
  "Branches",
  "Staging",
  "Commits",
  "Remote",
  "Undo",
  "History",
  "Tags",
  "Stash",
  "Advanced",
];

export const gitCommands: GitCommand[] = [
  // ─── Setup ───────────────────────────────────────────────────────────────
  {
    id: "init",
    name: "Initialize repo",
    description: "Create a new empty Git repository in the current directory.",
    command: "git init",
    tags: ["init", "new", "start", "create"],
    category: "Setup",
  },
  {
    id: "clone",
    name: "Clone repository",
    description: "Download a remote repository to a local directory.",
    command: "git clone <url>",
    tags: ["clone", "download", "remote"],
    category: "Setup",
  },
  {
    id: "clone-shallow",
    name: "Shallow clone",
    description: "Clone with only the latest commit — much faster for large repos.",
    command: "git clone --depth 1 <url>",
    tags: ["clone", "shallow", "fast", "depth"],
    category: "Setup",
  },
  {
    id: "config-name",
    name: "Set global username",
    description: "Set the name that will appear in all your commits.",
    command: 'git config --global user.name "Your Name"',
    tags: ["config", "name", "user", "global"],
    category: "Setup",
  },
  {
    id: "config-email",
    name: "Set global email",
    description: "Set the email that will appear in all your commits.",
    command: 'git config --global user.email "you@example.com"',
    tags: ["config", "email", "user", "global"],
    category: "Setup",
  },
  {
    id: "config-list",
    name: "List config",
    description: "Show all current Git configuration settings.",
    command: "git config --list",
    tags: ["config", "list", "settings"],
    category: "Setup",
  },
  {
    id: "config-editor",
    name: "Set default editor",
    description: "Change the editor used for commit messages (e.g., VS Code).",
    command: "git config --global core.editor \"code --wait\"",
    tags: ["config", "editor", "vscode"],
    category: "Setup",
  },

  // ─── Branches ─────────────────────────────────────────────────────────────
  {
    id: "branch-list",
    name: "List branches",
    description: "Show all local branches. Add -a to include remote branches.",
    command: "git branch",
    tags: ["branch", "list", "show"],
    category: "Branches",
  },
  {
    id: "branch-list-all",
    name: "List all branches",
    description: "Show local and remote tracking branches.",
    command: "git branch -a",
    tags: ["branch", "list", "remote", "all"],
    category: "Branches",
  },
  {
    id: "branch-create",
    name: "Create branch",
    description: "Create a new branch without switching to it.",
    command: "git branch <branch-name>",
    tags: ["branch", "create", "new"],
    category: "Branches",
  },
  {
    id: "branch-switch",
    name: "Switch branch",
    description: "Switch to an existing branch.",
    command: "git switch <branch-name>",
    tags: ["switch", "checkout", "branch"],
    category: "Branches",
  },
  {
    id: "branch-switch-create",
    name: "Create & switch branch",
    description: "Create a new branch and switch to it in one step.",
    command: "git switch -c <branch-name>",
    tags: ["switch", "create", "checkout", "new", "branch"],
    category: "Branches",
  },
  {
    id: "branch-rename",
    name: "Rename branch",
    description: "Rename the current branch.",
    command: "git branch -m <new-name>",
    tags: ["branch", "rename", "move"],
    category: "Branches",
  },
  {
    id: "branch-delete",
    name: "Delete merged branch",
    description: "Delete a branch that has already been merged.",
    command: "git branch -d <branch-name>",
    tags: ["branch", "delete", "remove"],
    category: "Branches",
  },
  {
    id: "branch-delete-force",
    name: "Force delete branch",
    description: "Force-delete a branch even if it has unmerged changes.",
    command: "git branch -D <branch-name>",
    tags: ["branch", "delete", "force", "remove"],
    category: "Branches",
    warning: "Permanently deletes local changes on the branch if unmerged.",
  },
  {
    id: "merge",
    name: "Merge branch",
    description: "Merge another branch into the current branch.",
    command: "git merge <branch-name>",
    tags: ["merge", "branch", "integrate"],
    category: "Branches",
  },
  {
    id: "merge-no-ff",
    name: "Merge (no fast-forward)",
    description: "Merge with a merge commit even if fast-forward is possible — preserves branch history.",
    command: "git merge --no-ff <branch-name>",
    tags: ["merge", "no-ff", "commit", "history"],
    category: "Branches",
  },
  {
    id: "rebase",
    name: "Rebase onto branch",
    description: "Replay your commits on top of another branch for a linear history.",
    command: "git rebase <branch-name>",
    tags: ["rebase", "linear", "history"],
    category: "Branches",
    warning: "Rewrites commit history. Never rebase shared/published branches.",
  },
  {
    id: "rebase-interactive",
    name: "Interactive rebase",
    description: "Squash, reorder, or edit the last N commits interactively.",
    command: "git rebase -i HEAD~<n>",
    tags: ["rebase", "interactive", "squash", "amend", "history"],
    category: "Branches",
    warning: "Rewrites commit history. Avoid on branches others have pulled.",
  },

  // ─── Staging ──────────────────────────────────────────────────────────────
  {
    id: "status",
    name: "Show status",
    description: "Show the working tree status — modified, staged, and untracked files.",
    command: "git status",
    tags: ["status", "changes", "modified"],
    category: "Staging",
  },
  {
    id: "add-all",
    name: "Stage all changes",
    description: "Stage all modified and new files for the next commit.",
    command: "git add .",
    tags: ["add", "stage", "all"],
    category: "Staging",
  },
  {
    id: "add-file",
    name: "Stage a file",
    description: "Stage a specific file for the next commit.",
    command: "git add <file>",
    tags: ["add", "stage", "file"],
    category: "Staging",
  },
  {
    id: "add-patch",
    name: "Stage interactively (patch)",
    description: "Interactively select hunks within files to stage — great for partial commits.",
    command: "git add -p",
    tags: ["add", "patch", "interactive", "hunk", "partial"],
    category: "Staging",
  },
  {
    id: "diff",
    name: "Show unstaged diff",
    description: "Show changes in the working tree that are not yet staged.",
    command: "git diff",
    tags: ["diff", "changes", "unstaged"],
    category: "Staging",
  },
  {
    id: "diff-staged",
    name: "Show staged diff",
    description: "Show changes that are staged and ready to commit.",
    command: "git diff --staged",
    tags: ["diff", "staged", "index", "cached"],
    category: "Staging",
  },
  {
    id: "restore",
    name: "Discard file changes",
    description: "Discard unstaged changes in a file, restoring it to the last commit.",
    command: "git restore <file>",
    tags: ["restore", "discard", "undo", "revert"],
    category: "Staging",
    warning: "Permanently discards uncommitted changes in that file.",
  },
  {
    id: "restore-staged",
    name: "Unstage a file",
    description: "Remove a file from the staging area without discarding its changes.",
    command: "git restore --staged <file>",
    tags: ["restore", "unstage", "staged", "remove"],
    category: "Staging",
  },

  // ─── Commits ──────────────────────────────────────────────────────────────
  {
    id: "commit",
    name: "Commit staged changes",
    description: "Create a commit with a message from all staged changes.",
    command: 'git commit -m "your message"',
    tags: ["commit", "save", "message"],
    category: "Commits",
  },
  {
    id: "commit-all",
    name: "Stage & commit tracked files",
    description: "Stage all changes to tracked files and commit in one step.",
    command: 'git commit -am "your message"',
    tags: ["commit", "add", "all", "stage"],
    category: "Commits",
  },
  {
    id: "commit-amend",
    name: "Amend last commit message",
    description: "Change the message of the most recent commit.",
    command: "git commit --amend",
    tags: ["amend", "edit", "message", "last"],
    category: "Commits",
    warning: "Rewrites the last commit. Don't amend commits already pushed.",
  },
  {
    id: "commit-amend-no-edit",
    name: "Amend last commit (keep message)",
    description: "Add staged changes to the last commit without changing its message.",
    command: "git commit --amend --no-edit",
    tags: ["amend", "fixup", "no-edit"],
    category: "Commits",
    warning: "Rewrites the last commit. Don't amend commits already pushed.",
  },

  // ─── Remote ───────────────────────────────────────────────────────────────
  {
    id: "remote-add",
    name: "Add remote origin",
    description: "Connect the local repo to a remote repository URL.",
    command: "git remote add origin <url>",
    tags: ["remote", "add", "origin", "connect"],
    category: "Remote",
  },
  {
    id: "remote-list",
    name: "List remotes",
    description: "Show all configured remote connections and their URLs.",
    command: "git remote -v",
    tags: ["remote", "list", "verbose", "url"],
    category: "Remote",
  },
  {
    id: "fetch",
    name: "Fetch from remote",
    description: "Download changes from remote without merging into local branches.",
    command: "git fetch",
    tags: ["fetch", "download", "remote"],
    category: "Remote",
  },
  {
    id: "pull",
    name: "Pull changes",
    description: "Fetch and merge changes from the remote tracking branch.",
    command: "git pull",
    tags: ["pull", "fetch", "merge", "sync"],
    category: "Remote",
  },
  {
    id: "pull-rebase",
    name: "Pull with rebase",
    description: "Fetch remote changes and rebase your local commits on top — keeps history linear.",
    command: "git pull --rebase",
    tags: ["pull", "rebase", "sync", "linear"],
    category: "Remote",
  },
  {
    id: "push",
    name: "Push to remote",
    description: "Upload local commits to the remote branch.",
    command: "git push origin <branch-name>",
    tags: ["push", "upload", "remote"],
    category: "Remote",
  },
  {
    id: "push-set-upstream",
    name: "Push & set upstream",
    description: "Push and set the remote as the default tracking branch for future pulls.",
    command: "git push -u origin <branch-name>",
    tags: ["push", "upstream", "track", "origin"],
    category: "Remote",
  },
  {
    id: "push-force-with-lease",
    name: "Force push (safe)",
    description: "Force push only if nobody else has pushed since your last fetch — safer than --force.",
    command: "git push --force-with-lease",
    tags: ["push", "force", "safe", "overwrite"],
    category: "Remote",
    warning: "Still overwrites remote history. Only use on your own feature branches.",
  },

  // ─── Undo ─────────────────────────────────────────────────────────────────
  {
    id: "revert",
    name: "Revert a commit",
    description: "Create a new commit that undoes the changes of a previous commit — safe for shared branches.",
    command: "git revert <commit-hash>",
    tags: ["revert", "undo", "safe", "commit"],
    category: "Undo",
  },
  {
    id: "reset-soft",
    name: "Reset (soft) — undo commit, keep staged",
    description: "Move HEAD back one commit, keeping changes staged. Use to re-commit with a different message.",
    command: "git reset --soft HEAD~1",
    tags: ["reset", "soft", "undo", "commit"],
    category: "Undo",
    warning: "Rewrites history. Don't use on pushed commits.",
  },
  {
    id: "reset-mixed",
    name: "Reset (mixed) — undo commit, keep files",
    description: "Move HEAD back one commit and unstage changes, but keep your file edits.",
    command: "git reset HEAD~1",
    tags: ["reset", "mixed", "undo", "unstage"],
    category: "Undo",
    warning: "Rewrites history. Don't use on pushed commits.",
  },
  {
    id: "reset-hard",
    name: "Reset (hard) — discard everything",
    description: "Move HEAD back one commit and permanently discard all changes.",
    command: "git reset --hard HEAD~1",
    tags: ["reset", "hard", "discard", "permanent"],
    category: "Undo",
    warning: "DESTRUCTIVE — permanently deletes uncommitted changes and the last commit.",
  },
  {
    id: "clean",
    name: "Remove untracked files",
    description: "Delete untracked files and directories from the working tree.",
    command: "git clean -fd",
    tags: ["clean", "untracked", "delete", "remove"],
    category: "Undo",
    warning: "DESTRUCTIVE — permanently deletes files not tracked by Git.",
  },

  // ─── History ──────────────────────────────────────────────────────────────
  {
    id: "log",
    name: "Show commit log",
    description: "List commits with author, date, and full message.",
    command: "git log",
    tags: ["log", "history", "commits"],
    category: "History",
  },
  {
    id: "log-oneline",
    name: "Show compact log",
    description: "Show each commit on a single line — short hash and subject.",
    command: "git log --oneline",
    tags: ["log", "oneline", "compact", "history"],
    category: "History",
  },
  {
    id: "log-graph",
    name: "Show branch graph",
    description: "Show commit history as a visual ASCII graph with all branches.",
    command: "git log --oneline --graph --all",
    tags: ["log", "graph", "branches", "visual", "tree"],
    category: "History",
  },
  {
    id: "show",
    name: "Show a commit",
    description: "Display the diff and metadata for a specific commit.",
    command: "git show <commit-hash>",
    tags: ["show", "commit", "diff", "inspect"],
    category: "History",
  },
  {
    id: "blame",
    name: "Blame a file",
    description: "Show which commit and author last modified each line of a file.",
    command: "git blame <file>",
    tags: ["blame", "author", "line", "who", "annotate"],
    category: "History",
  },
  {
    id: "log-file",
    name: "File history",
    description: "Show the commit history for a specific file.",
    command: "git log --follow -p <file>",
    tags: ["log", "file", "history", "follow"],
    category: "History",
  },
  {
    id: "diff-commits",
    name: "Diff between commits",
    description: "Show differences between two commits or branches.",
    command: "git diff <commit-a>..<commit-b>",
    tags: ["diff", "compare", "commits", "between"],
    category: "History",
  },

  // ─── Tags ─────────────────────────────────────────────────────────────────
  {
    id: "tag-list",
    name: "List tags",
    description: "Show all tags in the repository.",
    command: "git tag",
    tags: ["tag", "list", "version"],
    category: "Tags",
  },
  {
    id: "tag-lightweight",
    name: "Create lightweight tag",
    description: "Create a lightweight tag pointing to the current commit.",
    command: "git tag <tag-name>",
    tags: ["tag", "create", "lightweight"],
    category: "Tags",
  },
  {
    id: "tag-annotated",
    name: "Create annotated tag",
    description: "Create an annotated tag with a message — recommended for releases.",
    command: 'git tag -a <tag-name> -m "Release message"',
    tags: ["tag", "annotated", "release", "version"],
    category: "Tags",
  },
  {
    id: "tag-push",
    name: "Push all tags",
    description: "Push all local tags to the remote.",
    command: "git push origin --tags",
    tags: ["tag", "push", "remote"],
    category: "Tags",
  },
  {
    id: "tag-delete",
    name: "Delete local tag",
    description: "Remove a tag from the local repository.",
    command: "git tag -d <tag-name>",
    tags: ["tag", "delete", "remove"],
    category: "Tags",
  },
  {
    id: "tag-delete-remote",
    name: "Delete remote tag",
    description: "Remove a tag that was already pushed to the remote.",
    command: "git push origin --delete <tag-name>",
    tags: ["tag", "delete", "remote"],
    category: "Tags",
  },

  // ─── Stash ────────────────────────────────────────────────────────────────
  {
    id: "stash",
    name: "Stash changes",
    description: "Save uncommitted changes to a temporary shelf so you can switch branches.",
    command: "git stash",
    tags: ["stash", "save", "temporary"],
    category: "Stash",
  },
  {
    id: "stash-named",
    name: "Stash with message",
    description: "Stash changes with a descriptive name for easier identification later.",
    command: 'git stash push -m "stash description"',
    tags: ["stash", "message", "named"],
    category: "Stash",
  },
  {
    id: "stash-pop",
    name: "Pop latest stash",
    description: "Apply the most recent stash and remove it from the stash list.",
    command: "git stash pop",
    tags: ["stash", "pop", "apply", "restore"],
    category: "Stash",
  },
  {
    id: "stash-list",
    name: "List stashes",
    description: "Show all stashed changes.",
    command: "git stash list",
    tags: ["stash", "list", "show"],
    category: "Stash",
  },
  {
    id: "stash-apply",
    name: "Apply stash (keep it)",
    description: "Apply a specific stash without removing it from the list.",
    command: "git stash apply stash@{<n>}",
    tags: ["stash", "apply", "keep"],
    category: "Stash",
  },
  {
    id: "stash-drop",
    name: "Drop a stash",
    description: "Remove a specific stash entry without applying it.",
    command: "git stash drop stash@{<n>}",
    tags: ["stash", "drop", "delete"],
    category: "Stash",
  },

  // ─── Advanced ─────────────────────────────────────────────────────────────
  {
    id: "cherry-pick",
    name: "Cherry-pick commit",
    description: "Apply changes from a specific commit onto the current branch.",
    command: "git cherry-pick <commit-hash>",
    tags: ["cherry-pick", "apply", "commit", "port"],
    category: "Advanced",
  },
  {
    id: "reflog",
    name: "Show reflog",
    description: "Show a log of all HEAD movements — useful for recovering 'lost' commits after reset.",
    command: "git reflog",
    tags: ["reflog", "recover", "lost", "history"],
    category: "Advanced",
  },
  {
    id: "bisect-start",
    name: "Start bisect",
    description: "Begin a binary search to find which commit introduced a bug.",
    command: "git bisect start",
    tags: ["bisect", "debug", "find", "bug"],
    category: "Advanced",
  },
  {
    id: "shortlog",
    name: "Contribution summary",
    description: "Show commit counts grouped by author — useful for changelogs.",
    command: "git shortlog -sn",
    tags: ["shortlog", "author", "contributors", "summary"],
    category: "Advanced",
  },
  {
    id: "worktree-add",
    name: "Add worktree",
    description: "Check out a branch into a separate directory — work on two branches simultaneously.",
    command: "git worktree add ../<dir> <branch-name>",
    tags: ["worktree", "parallel", "checkout"],
    category: "Advanced",
  },
  {
    id: "submodule-add",
    name: "Add submodule",
    description: "Include another Git repository as a subdirectory of your project.",
    command: "git submodule add <url> <path>",
    tags: ["submodule", "dependency", "nested"],
    category: "Advanced",
  },
  {
    id: "archive",
    name: "Archive repository",
    description: "Create a zip/tar archive of the repo at a specific commit without .git history.",
    command: "git archive --format=zip HEAD > repo.zip",
    tags: ["archive", "zip", "export", "download"],
    category: "Advanced",
  },
  {
    id: "hooks",
    name: "List available hooks",
    description: "Show the hooks available in the .git/hooks directory.",
    command: "ls .git/hooks",
    tags: ["hooks", "pre-commit", "post-commit", "automation"],
    category: "Advanced",
  },
];
