// Common, unambiguous English words (4-8 letters, no homophones or offensive
// terms) — a browser-friendly wordlist in the spirit of the diceware method.
// Entropy per word is computed dynamically from this list's actual length.
export const PASSPHRASE_WORDS: string[] = [
  "acid", "actor", "adapt", "agent", "alarm", "album", "alert", "alien",
  "alloy", "alpha", "amber", "anchor", "angle", "animal", "apple", "arch",
  "arena", "armor", "arrow", "artist", "ash", "aspect", "atlas", "atom",
  "aunt", "author", "autumn", "avenue", "badge", "baker", "banjo", "barrel",
  "basil", "basin", "basket", "beacon", "beam", "bear", "beaver", "bell",
  "belt", "bench", "berry", "bike", "bird", "bison", "blade", "blanket",
  "blast", "bloom", "blue", "boat", "bolt", "bone", "bonus", "book",
  "boost", "border", "botany", "bottle", "boulder", "bow", "box", "branch",
  "brave", "bread", "breeze", "brick", "bridge", "bright", "broom", "brown",
  "brush", "bubble", "bucket", "buddy", "budget", "bulb", "bull", "bunker",
  "cabin", "cable", "cactus", "camel", "camera", "camp", "canal", "candle",
  "canoe", "canvas", "canyon", "cape", "captain", "carbon", "cargo", "carpet",
  "castle", "cave", "cedar", "cement", "chain", "chair", "chalk", "channel",
  "chapter", "charm", "chart", "cheese", "cherry", "chess", "chief", "circle",
  "citrus", "city", "clay", "cliff", "cloak", "clock", "cloud", "clover",
  "coast", "cobalt", "coffee", "coil", "comet", "compass", "copper", "coral",
  "corner", "cotton", "cradle", "crane", "crater", "cream", "creek", "crescent",
  "crew", "cricket", "cross", "crown", "crystal", "cube", "curve", "custom",
  "cypress", "dagger", "daisy", "dawn", "deck", "delta", "denim", "depth",
  "desert", "diamond", "dish", "dolphin", "domain", "donkey", "dragon", "drift",
  "drum", "duck", "dune", "eagle", "earth", "east", "echo", "eden",
  "eel", "elbow", "ember", "emerald", "engine", "envoy", "equal", "estate",
  "ethics", "event", "expert", "fabric", "falcon", "fern", "fiber", "field",
  "finch", "flame", "flare", "flask", "fleet", "flint", "float", "flock",
  "flower", "flute", "foam", "forest", "forge", "fossil", "fountain", "fox",
  "frame", "frost", "fruit", "galaxy", "garden", "gate", "gecko", "gem",
  "giant", "glacier", "glass", "globe", "glow", "goat", "gold", "gorge",
  "grain", "grape", "graph", "grass", "gravel", "grove", "guitar", "gull",
  "habit", "hammer", "harbor", "harvest", "hawk", "hazel", "heron", "hill",
  "honey", "hoof", "horizon", "hornet", "hydro", "ice", "igloo", "index",
  "indigo", "inlet", "iris", "island", "ivory", "jade", "jaguar", "jasper",
  "jelly", "jet", "jewel", "joker", "jolt", "jungle", "kayak", "kernel",
  "kettle", "kite", "kiwi", "knight", "koala", "lagoon", "lake", "lamp",
];
