export const devPhrases = [
  // Classic dev humor
  "Works on my machine. ¯\\_(ツ)_/¯",
  "It's not a bug, it's an undocumented feature.",
  "Have you tried turning it off and on again?",
  "sudo make me a sandwich.",
  "There are only 10 types of people: those who understand binary and those who don't.",
  "99 little bugs in the code... take one down, patch it around... 127 little bugs in the code.",
  "It works in production. Don't touch it.",
  "git commit -m 'fixed stuff'",
  "// TODO: fix this later  (written 3 years ago)",
  "console.log('why is this not working')",
  "rm -rf and pray.",
  "It's always DNS.",
  "The cloud is just someone else's computer.",
  "Stack Overflow is down. Everyone panic.",
  "Code never lies. Comments sometimes do.",
  "First rule of programming: if it works, don't touch it.",
  "A SQL query walks into a bar and asks two tables... 'Can I join you?'",
  "Why do programmers prefer dark mode? Because light attracts bugs.",
  "I don't always test my code, but when I do, I do it in production.",
  "Keyboard not found. Press F1 to continue.",
  "Real programmers count from 0.",
  "It's case sensitive. It's always case sensitive.",
  "404: Sleep not found.",
  "My code works and I have no idea why.",
  "Debugging: being the detective in a crime movie where you are also the murderer.",
  "undefined is not a function.",
  "Works fine in dev. Ship it.",
  "The best code is no code at all.",
  "Documentation? The code is self-explanatory.",
  "It worked yesterday, I swear.",
  "Just one more feature and then I'll refactor.",
  "Tab vs spaces? Choose wisely or die.",
  "Never trust a computer you can't throw out a window.",
  "Programming is 10% writing code and 90% figuring out why it doesn't work.",
  "Hello World! ...and that's as far as I got.",
  "Any fool can write code a computer understands. Good luck writing code humans can.",
  "Senior dev: someone who has made all the same mistakes, but faster.",
  "The code is clean. The developer is not.",
  "coffee.init() → developer.start()",
  "Programmer: a machine that turns coffee into code.",
  "chmod 777 and hope for the best.",
  "Have you checked the logs? No? Check the logs.",
  "Semicolons save lives. Mostly the developer's.",
  "In case of fire: git commit, git push, leave building.",
  "It's not slow, it's just... thinking.",
  "One does not simply deploy on Friday.",
  "Keep calm and clear the cache.",
  "pip install works_on_my_machine",
  "npm install — making node_modules the heaviest object in the universe.",
  "Turning coffee into TypeScript errors since 2024.",
];
