export const devPhrases = [
  "Works on my machine. ¯\\_(ツ)_/¯",
  "It's always DNS.",
  "rm -rf and pray.",
  "git commit -m 'fix' && git push --force",
  "Have you tried turning it off and on again?",
  "It's not a bug, it's an undocumented feature.",
  "// TODO: fix this later (written in 2019)",
  "Stack Overflow to the rescue, again.",
  "undefined is not a function.",
  "The cloud is just someone else's computer.",
  "sudo make me a sandwich.",
  "There are only 10 types of people: those who understand binary and those who don't.",
  "Why does it work? No idea. Shipping it anyway.",
  "A semicolon costs nothing. A missing semicolon costs hours.",
  "Tabs vs spaces. Choose wisely.",
  "git blame never lies.",
  "console.log('here') console.log('here2') console.log('WHY')",
  "npm install... still running...",
  "It worked yesterday, I swear.",
  "The code is self-documenting (it's not).",
  "Copy-paste from Stack Overflow. Time to production: 4 minutes.",
  "Every good developer is essentially a professional Googler.",
  "Premature optimization is the root of all evil. So is premature pushes.",
  "Keep calm and clear the cache.",
  "In case of fire: git commit, git push, leave building.",
  "I don't always test my code, but when I do, I do it in production.",
  "Debugging is like being the detective in a crime thriller where you're also the murderer.",
  "Software is like entropy: it's always increasing.",
  "99 little bugs in the code, 99 little bugs… take one down, patch it around… 127 little bugs in the code.",
  "What part of `<!-- -->` don't you understand?",
  "I have not failed. I've just found 10,000 ways that won't work.",
  "The best error message is the one that never shows up.",
  "It compiles? Ship it.",
  "My code doesn't have bugs. It has randomly activated features.",
  "Always code as if the person who ends up maintaining your code will be a violent psychopath who knows where you live.",
  "Legacy code: someone else's problem until it's your problem.",
  "First, solve the problem. Then, write the code.",
  "Any fool can write code that a computer can understand. Good programmers write code that humans can understand.",
  "It's not slow, it's loading.",
  "The DevTools lied.",
  "No, seriously, it's always DNS.",
  "import *, hope for the best.",
  "Production is just staging with extra steps.",
  "404: motivation not found.",
  "Move fast and break things. Then fix things slowly.",
  "Ship it, log it, deny it.",
  "Reading someone else's code is an extreme sport.",
  "If it's stupid but it works, it's not stupid.",
  "Any code that I haven't touched in 6 months might as well have been written by someone else.",
  "Docs are like wine — rare, precious, and usually from three years ago.",
];
