export interface RegexPattern {
  id: string;
  name: string;
  pattern: string;
  flags: string;
  testString: string;
  description: string;
  category: string;
  tags: string[];
}

export const regexPatterns: RegexPattern[] = [

  // ── Validation ────────────────────────────────────────────────────────────
  {
    id: "email",
    name: "Email Address",
    pattern: "^[a-zA-Z0-9._%+\\-]+@[a-zA-Z0-9.\\-]+\\.[a-zA-Z]{2,}$",
    flags: "i",
    testString: "user@example.com\ninvalid-email\ntest.user+label@domain.co.uk",
    description: "Validates standard email addresses including subdomains and plus addressing",
    category: "Validation",
    tags: ["email", "validation", "form", "input"],
  },
  {
    id: "url",
    name: "URL (http/https)",
    pattern: "https?:\\/\\/(www\\.)?[-a-zA-Z0-9@:%._\\+~#=]{1,256}\\.[a-zA-Z0-9()]{1,6}\\b([-a-zA-Z0-9()@:%_\\+.~#?&\\/\\/=]*)",
    flags: "gi",
    testString: "Visit https://toolninja.io or http://example.com/path?query=1",
    description: "Matches HTTP and HTTPS URLs including paths, query strings and fragments",
    category: "Validation",
    tags: ["url", "link", "http", "https", "validation"],
  },
  {
    id: "ipv4",
    name: "IPv4 Address",
    pattern: "\\b(?:(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\\.){3}(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\\b",
    flags: "g",
    testString: "Server at 192.168.1.1 and 10.0.0.1. Invalid: 999.999.999.999",
    description: "Matches valid IPv4 addresses (0.0.0.0 to 255.255.255.255)",
    category: "Validation",
    tags: ["ip", "ipv4", "network", "address"],
  },
  {
    id: "ipv6",
    name: "IPv6 Address",
    pattern: "([0-9a-fA-F]{1,4}:){7}[0-9a-fA-F]{1,4}",
    flags: "gi",
    testString: "2001:0db8:85a3:0000:0000:8a2e:0370:7334",
    description: "Matches full IPv6 addresses in colon-hex notation",
    category: "Validation",
    tags: ["ip", "ipv6", "network", "address"],
  },
  {
    id: "phone-us",
    name: "US Phone Number",
    pattern: "\\(?\\d{3}\\)?[\\s.\\-]?\\d{3}[\\s.\\-]?\\d{4}",
    flags: "g",
    testString: "(555) 123-4567\n555.123.4567\n5551234567\n+1 555 123 4567",
    description: "Matches US phone numbers in various formats",
    category: "Validation",
    tags: ["phone", "us", "telephone", "validation"],
  },
  {
    id: "password-strong",
    name: "Strong Password",
    pattern: "^(?=.*[a-z])(?=.*[A-Z])(?=.*\\d)(?=.*[@$!%*?&])[A-Za-z\\d@$!%*?&]{8,}$",
    flags: "",
    testString: "WeakPass\nStr0ng@Pass\nNoSpecial1\nshort@1A",
    description: "Requires 8+ chars with uppercase, lowercase, number and special character",
    category: "Validation",
    tags: ["password", "security", "validation", "strength"],
  },
  {
    id: "credit-card",
    name: "Credit Card Number",
    pattern: "\\b(?:\\d[ \\-]?){13,16}\\b",
    flags: "g",
    testString: "4532015112830366\n4532 0151 1283 0366\n4532-0151-1283-0366",
    description: "Matches 13-16 digit credit card numbers with optional spaces or dashes",
    category: "Validation",
    tags: ["credit card", "payment", "validation"],
  },
  {
    id: "zip-us",
    name: "US ZIP Code",
    pattern: "\\b\\d{5}(?:[\\-]\\d{4})?\\b",
    flags: "g",
    testString: "90210\n90210-1234\n12345",
    description: "Matches 5-digit US ZIP codes with optional 4-digit extension",
    category: "Validation",
    tags: ["zip", "postal", "us", "address"],
  },
  {
    id: "mac-address",
    name: "MAC Address",
    pattern: "([0-9A-Fa-f]{2}[:\\-]){5}([0-9A-Fa-f]{2})",
    flags: "gi",
    testString: "00:1A:2B:3C:4D:5E\n00-1A-2B-3C-4D-5E",
    description: "Matches MAC addresses with colon or hyphen separators",
    category: "Validation",
    tags: ["mac", "network", "hardware", "address"],
  },

  // ── Dates & Times ─────────────────────────────────────────────────────────
  {
    id: "date-iso",
    name: "ISO Date (YYYY-MM-DD)",
    pattern: "\\b\\d{4}-(0[1-9]|1[0-2])-(0[1-9]|[12]\\d|3[01])\\b",
    flags: "g",
    testString: "2024-01-15\n2024-13-01 invalid\n1999-12-31",
    description: "Matches ISO 8601 date format with valid month and day ranges",
    category: "Dates & Times",
    tags: ["date", "iso", "yyyy-mm-dd", "datetime"],
  },
  {
    id: "date-us",
    name: "US Date (MM/DD/YYYY)",
    pattern: "(0?[1-9]|1[0-2])\\/(0?[1-9]|[12]\\d|3[01])\\/(19|20)\\d{2}",
    flags: "g",
    testString: "01/15/2024\n12/31/1999\n13/01/2024 invalid",
    description: "Matches US-format dates MM/DD/YYYY with 1900-2099 year range",
    category: "Dates & Times",
    tags: ["date", "us", "mm/dd/yyyy"],
  },
  {
    id: "time-24h",
    name: "Time (24-hour)",
    pattern: "\\b([01]?[0-9]|2[0-3]):([0-5][0-9])(?::([0-5][0-9]))?\\b",
    flags: "g",
    testString: "09:30\n23:59:59\n00:00\n24:00 invalid",
    description: "Matches 24-hour time format HH:MM with optional seconds",
    category: "Dates & Times",
    tags: ["time", "24h", "clock", "datetime"],
  },
  {
    id: "time-12h",
    name: "Time (12-hour AM/PM)",
    pattern: "\\b(1[0-2]|0?[1-9]):([0-5][0-9])\\s?(AM|PM|am|pm)\\b",
    flags: "gi",
    testString: "09:30 AM\n12:00 PM\n1:45pm",
    description: "Matches 12-hour time format with AM/PM",
    category: "Dates & Times",
    tags: ["time", "12h", "am", "pm", "clock"],
  },
  {
    id: "unix-timestamp",
    name: "Unix Timestamp",
    pattern: "\\b(1[0-9]{9}|[2-9][0-9]{9})\\b",
    flags: "g",
    testString: "1715000000\n1000000000\n9999999999",
    description: "Matches Unix timestamps (seconds) in valid range",
    category: "Dates & Times",
    tags: ["unix", "timestamp", "epoch"],
  },

  // ── Programming ───────────────────────────────────────────────────────────
  {
    id: "hex-color",
    name: "HEX Color Code",
    pattern: "#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})\\b",
    flags: "gi",
    testString: "#a855f7\n#FFF\n#GGGGGG invalid\n#ff0000",
    description: "Matches 3 or 6 digit hex color codes with # prefix",
    category: "Programming",
    tags: ["color", "hex", "css", "design"],
  },
  {
    id: "css-class",
    name: "CSS Class Selector",
    pattern: "\\.[a-zA-Z_\\-][a-zA-Z0-9_\\-]*",
    flags: "g",
    testString: ".container .nav-item .btn-primary _invalid",
    description: "Matches valid CSS class selectors",
    category: "Programming",
    tags: ["css", "class", "selector", "html"],
  },
  {
    id: "html-tag",
    name: "HTML Tag",
    pattern: "<\\/?[a-zA-Z][a-zA-Z0-9]*(?:\\s+[a-zA-Z\\-]+(?:=(?:\"[^\"]*\"|'[^']*'|[^\\s>]*))?)*\\s*\\/?>",
    flags: "gi",
    testString: "<div class=\"container\">\n<img src=\"test.jpg\" />\n<br>\n</span>",
    description: "Matches HTML opening, closing and self-closing tags",
    category: "Programming",
    tags: ["html", "tag", "markup"],
  },
  {
    id: "version-semver",
    name: "Semantic Version",
    pattern: "\\bv?(0|[1-9]\\d*)\\.(0|[1-9]\\d*)\\.(0|[1-9]\\d*)(?:-((?:0|[1-9]\\d*|\\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\\.(?:0|[1-9]\\d*|\\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\\+([0-9a-zA-Z-]+(?:\\.[0-9a-zA-Z-]+)*))?\\b",
    flags: "g",
    testString: "v1.0.0\n2.3.1-beta.1\n1.0.0-alpha+001\n0.0.1",
    description: "Matches semantic version numbers (SemVer) with optional pre-release and build metadata",
    category: "Programming",
    tags: ["semver", "version", "npm", "release"],
  },
  {
    id: "json-key",
    name: "JSON Key",
    pattern: "\"([^\"]+)\":",
    flags: "g",
    testString: "{\"name\": \"John\", \"age\": 30, \"active\": true}",
    description: "Extracts all keys from a JSON object",
    category: "Programming",
    tags: ["json", "key", "object", "parse"],
  },
  {
    id: "uuid",
    name: "UUID v4",
    pattern: "\\b[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}\\b",
    flags: "gi",
    testString: "550e8400-e29b-41d4-a716-446655440000\nnot-a-uuid\n6ba7b810-9dad-11d1-80b4-00c04fd430c8",
    description: "Matches valid UUID v4 identifiers",
    category: "Programming",
    tags: ["uuid", "guid", "identifier"],
  },
  {
    id: "base64",
    name: "Base64 String",
    pattern: "^(?:[A-Za-z0-9+\\/]{4})*(?:[A-Za-z0-9+\\/]{2}==|[A-Za-z0-9+\\/]{3}=)?$",
    flags: "",
    testString: "SGVsbG8gV29ybGQ=\ndGVzdA==\nnotbase64!@#",
    description: "Validates Base64 encoded strings including padding",
    category: "Programming",
    tags: ["base64", "encoding", "decode"],
  },
  {
    id: "jwt",
    name: "JWT Token",
    pattern: "^[A-Za-z0-9_\\-]+\\.[A-Za-z0-9_\\-]+\\.[A-Za-z0-9_\\-]*$",
    flags: "",
    testString: "eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1c2VyIn0.abc123\nnot.a.valid.jwt.token",
    description: "Matches JSON Web Token (JWT) format: header.payload.signature",
    category: "Programming",
    tags: ["jwt", "token", "auth", "security"],
  },
  {
    id: "markdown-link",
    name: "Markdown Link",
    pattern: "\\[([^\\[\\]]+)\\]\\(([^()]+)\\)",
    flags: "g",
    testString: "[ToolNinja](https://toolninja.io)\n[Click here](https://example.com \"title\")",
    description: "Matches Markdown link syntax [text](url)",
    category: "Programming",
    tags: ["markdown", "link", "url", "text"],
  },

  // ── Data Extraction ───────────────────────────────────────────────────────
  {
    id: "hashtag",
    name: "Hashtag",
    pattern: "#[A-Za-z0-9_]+",
    flags: "g",
    testString: "Love #coding and #WebDev! Check #toolninja.io",
    description: "Extracts hashtags from social media text",
    category: "Data Extraction",
    tags: ["hashtag", "social", "twitter", "instagram"],
  },
  {
    id: "mentions",
    name: "@Mentions",
    pattern: "@[A-Za-z0-9_]+",
    flags: "g",
    testString: "Hey @user1 and @john_doe, check this out!",
    description: "Extracts @mentions from text",
    category: "Data Extraction",
    tags: ["mention", "social", "username"],
  },
  {
    id: "numbers-extract",
    name: "Extract Numbers",
    pattern: "-?\\d+\\.?\\d*",
    flags: "g",
    testString: "Price: $29.99, quantity: 3, discount: -5%",
    description: "Extracts all numbers (integers and decimals, including negative)",
    category: "Data Extraction",
    tags: ["number", "extract", "decimal", "integer"],
  },
  {
    id: "words-extract",
    name: "Extract Words Only",
    pattern: "\\b[a-zA-Z]+\\b",
    flags: "g",
    testString: "Hello World! 123 test_case foo-bar",
    description: "Extracts only pure alphabetic words, ignoring numbers and symbols",
    category: "Data Extraction",
    tags: ["word", "extract", "text", "alphabetic"],
  },
  {
    id: "duplicate-words",
    name: "Duplicate Words",
    pattern: "\\b(\\w+)\\s+\\1\\b",
    flags: "gi",
    testString: "The the quick brown fox fox jumped",
    description: "Finds duplicate consecutive words in text",
    category: "Data Extraction",
    tags: ["duplicate", "word", "text", "nlp"],
  },
  {
    id: "log-error",
    name: "Log Error Lines",
    pattern: "^.*(ERROR|FATAL|CRITICAL).*$",
    flags: "gim",
    testString: "INFO Server started\nERROR Connection refused\nDEBUG Processing\nFATAL Out of memory",
    description: "Extracts ERROR, FATAL, and CRITICAL lines from log files",
    category: "Data Extraction",
    tags: ["log", "error", "debug", "devops"],
  },
  {
    id: "file-extension",
    name: "File Extension",
    pattern: "\\.(\\w+)$",
    flags: "gim",
    testString: "document.pdf\nimage.jpg\nscript.js\nstyle.min.css",
    description: "Extracts file extensions from filenames",
    category: "Data Extraction",
    tags: ["file", "extension", "path"],
  },
  {
    id: "filepath",
    name: "Unix File Path",
    pattern: "(\\/[\\w\\-\\.]+)+",
    flags: "g",
    testString: "/home/user/documents/file.txt\n/var/log/nginx/access.log\n/usr/local/bin",
    description: "Matches Unix/Linux absolute file paths",
    category: "Data Extraction",
    tags: ["path", "unix", "linux", "file"],
  },

  // ── Text Processing ───────────────────────────────────────────────────────
  {
    id: "empty-lines",
    name: "Empty Lines",
    pattern: "^\\s*$",
    flags: "gm",
    testString: "Line one\n\nLine three\n   \nLine five",
    description: "Matches blank or whitespace-only lines",
    category: "Text Processing",
    tags: ["empty", "blank", "line", "whitespace"],
  },
  {
    id: "trim-whitespace",
    name: "Leading/Trailing Whitespace",
    pattern: "^\\s+|\\s+$",
    flags: "gm",
    testString: "   Hello World   \n   trim me   \nnormal line",
    description: "Matches leading and trailing whitespace on each line",
    category: "Text Processing",
    tags: ["whitespace", "trim", "space", "clean"],
  },
  {
    id: "html-strip",
    name: "Strip HTML Tags",
    pattern: "<[^>]*>",
    flags: "g",
    testString: "<p>Hello <strong>World</strong></p>\n<div class=\"test\">Content</div>",
    description: "Matches all HTML tags for removal — replace with empty string",
    category: "Text Processing",
    tags: ["html", "strip", "clean", "text"],
  },
  {
    id: "camelcase",
    name: "camelCase Words",
    pattern: "[A-Z][a-z]+|[a-z]+",
    flags: "g",
    testString: "camelCaseVariable\ngetUserName\nparseJSONResponse",
    description: "Splits camelCase identifiers into individual words",
    category: "Text Processing",
    tags: ["camelcase", "split", "words", "programming"],
  },
  {
    id: "consecutive-spaces",
    name: "Consecutive Spaces",
    pattern: " {2,}",
    flags: "g",
    testString: "Hello   World  this  has   extra   spaces",
    description: "Matches 2 or more consecutive spaces — replace with single space",
    category: "Text Processing",
    tags: ["space", "whitespace", "clean", "normalize"],
  },

  // ── Security ──────────────────────────────────────────────────────────────
  {
    id: "sql-injection",
    name: "SQL Injection Patterns",
    pattern: "('(''|[^'])*')|(;)|(\\/\\*)|(\\*\\/)|(--)|(\\bOR\\b|\\bAND\\b|\\bUNION\\b|\\bSELECT\\b|\\bDROP\\b|\\bINSERT\\b|\\bUPDATE\\b|\\bDELETE\\b)",
    flags: "gi",
    testString: "normal input\n' OR '1'='1\n1; DROP TABLE users--\nUNION SELECT * FROM users",
    description: "Detects common SQL injection attack patterns — for security validation",
    category: "Security",
    tags: ["sql", "injection", "security", "attack"],
  },
  {
    id: "xss-basic",
    name: "Basic XSS Patterns",
    pattern: "<script[^>]*>[\\s\\S]*?<\\/script>|on\\w+\\s*=|javascript:",
    flags: "gi",
    testString: "<script>alert('xss')</script>\n<img onerror=\"alert(1)\">\njavascript:void(0)",
    description: "Detects basic XSS attack vectors — for input sanitization",
    category: "Security",
    tags: ["xss", "security", "injection", "html"],
  },

  // ── DevOps ────────────────────────────────────────────────────────────────
  {
    id: "docker-image",
    name: "Docker Image Name",
    pattern: "^([a-z0-9]+(?:[._-][a-z0-9]+)*\\/)?([a-z0-9]+(?:[._-][a-z0-9]+)*)(:[a-zA-Z0-9._-]+)?$",
    flags: "",
    testString: "nginx\nnginx:latest\nnode:18-alpine\nmy-registry.com/myapp:v1.2.3",
    description: "Validates Docker image names with optional registry and tag",
    category: "DevOps",
    tags: ["docker", "container", "image", "devops"],
  },
  {
    id: "env-variable",
    name: ".env Variable",
    pattern: "^([A-Z_][A-Z0-9_]*)=(.*)$",
    flags: "gm",
    testString: "DATABASE_URL=postgres://localhost/mydb\nAPI_KEY=abc123\nDEBUG=true\ninvalid=LOWERCASE_KEY",
    description: "Matches environment variable declarations in .env files",
    category: "DevOps",
    tags: ["env", "environment", "config", "devops"],
  },
  {
    id: "git-commit",
    name: "Git Commit Hash",
    pattern: "\\b[0-9a-f]{7,40}\\b",
    flags: "gi",
    testString: "commit a1b2c3d\nfull: 4c2a9b1e3f8d7c6a5b4e3f2a1b0c9d8e7f6a5b4e\nshort: abc1234",
    description: "Matches Git commit hashes (7 to 40 hex characters)",
    category: "DevOps",
    tags: ["git", "commit", "hash", "version control"],
  },
];

export const patternCategories = [
  "All",
  "Validation",
  "Dates & Times",
  "Programming",
  "Data Extraction",
  "Text Processing",
  "Security",
  "DevOps",
] as const;
