export interface Tool {
  slug: string;
  name: string;
  description: string;
  icon: string;
  category: string;
  keywords: string[];
}

export const tools: Tool[] = [
  // ─── Format ───────────────────────────────────────────────────────────────
  {
    slug: "json-formatter",
    name: "JSON Formatter",
    description: "Format, validate and minify JSON instantly",
    icon: "Braces",
    category: "Format",
    keywords: [
      "json formatter", "json formatter online", "json beautifier",
      "json validator", "json pretty print", "format json online",
      "json viewer", "json lint", "json minifier", "beautify json",
      "json parser online", "json editor online", "validate json",
      "json pretty printer", "json formatter and validator",
    ],
  },
  {
    slug: "markdown-preview",
    name: "Markdown Preview",
    description: "Write and preview Markdown in real time",
    icon: "BookOpen",
    category: "Format",
    keywords: [
      "markdown preview", "markdown editor online", "markdown viewer",
      "markdown renderer", "markdown live preview", "markdown to html",
      "online markdown editor", "markdown converter", "md preview",
      "markdown formatter", "markdown previewer online",
    ],
  },
  {
    slug: "sql-formatter",
    name: "SQL Formatter",
    description: "Format and beautify SQL queries with dialect support",
    icon: "Database",
    category: "Format",
    keywords: [
      "sql formatter", "sql formatter online", "sql beautifier",
      "sql pretty print", "format sql online", "sql code formatter",
      "sql query formatter", "sql beautify", "sql indenter",
      "mysql formatter", "postgresql formatter", "sql query beautifier",
      "sql syntax formatter", "sql formatter free",
    ],
  },
  {
    slug: "html-formatter",
    name: "HTML Formatter",
    description: "Prettify and minify HTML markup instantly",
    icon: "FileCode2",
    category: "Format",
    keywords: [
      "html formatter", "html formatter online", "html beautifier",
      "html pretty print", "format html online", "html code formatter",
      "html minifier", "html beautify online", "html tidy online",
      "html cleaner", "html validator online", "html indenter",
    ],
  },

  // ─── Encode ───────────────────────────────────────────────────────────────
  {
    slug: "base64",
    name: "Base64 Encoder/Decoder",
    description: "Encode or decode Base64 strings instantly",
    icon: "Binary",
    category: "Encode",
    keywords: [
      "base64 encoder", "base64 decoder", "base64 encode online",
      "base64 decode online", "base64 converter", "encode base64",
      "decode base64", "base64 encoding", "base64 decoding",
      "base64 to text", "text to base64", "base64 online",
      "base64 encode decode", "base64 string decoder",
    ],
  },
  {
    slug: "url-encoder",
    name: "URL Encoder/Decoder",
    description: "Encode and decode URLs and query parameters",
    icon: "Link",
    category: "Encode",
    keywords: [
      "url encoder", "url decoder", "url encode online", "url decode online",
      "percent encoding", "url encoding decoder", "encode url online",
      "decode url online", "uri encoder", "uri decoder",
      "url percent encoder", "url special characters encoder",
      "query string encoder", "url encode decode",
    ],
  },
  {
    slug: "jwt-decoder",
    name: "JWT Decoder",
    description: "Decode and inspect JWT tokens instantly",
    icon: "KeyRound",
    category: "Encode",
    keywords: [
      "jwt decoder", "jwt decoder online", "decode jwt", "jwt parser",
      "json web token decoder", "jwt token decoder", "jwt debugger",
      "jwt inspector", "decode jwt token online", "jwt payload decoder",
      "jwt header decoder", "jwt decode free", "inspect jwt token",
      "jwt viewer", "jwt token viewer",
    ],
  },
  {
    slug: "hash-generator",
    name: "Hash Generator",
    description: "Generate SHA-1, SHA-256, SHA-384 and SHA-512 hashes",
    icon: "Fingerprint",
    category: "Encode",
    keywords: [
      "hash generator", "md5 generator", "sha256 generator",
      "sha1 generator", "sha512 generator", "hash calculator",
      "md5 hash online", "sha256 hash online", "generate hash online",
      "checksum generator", "hash string online", "crypto hash generator",
      "md5 checksum", "file hash generator", "text hash generator",
    ],
  },
  {
    slug: "html-entity",
    name: "HTML Entity Encoder",
    description: "Encode and decode HTML entities and special characters",
    icon: "FileCode",
    category: "Encode",
    keywords: [
      "html entity encoder", "html entity decoder", "html escape",
      "html unescape", "html entities converter", "encode html entities",
      "decode html entities", "html special characters encoder",
      "html escape online", "html entity converter online",
      "html encode decode", "xml escape online",
    ],
  },
  {
    slug: "image-to-base64",
    name: "Image to Base64",
    description: "Convert images to Base64 data URIs for embedding",
    icon: "ImageIcon",
    category: "Encode",
    keywords: [
      "image to base64", "image to base64 converter", "convert image to base64",
      "base64 image encoder", "image base64 online", "png to base64",
      "jpg to base64", "base64 image string", "embed image base64",
      "data uri generator", "image data uri", "base64 encode image online",
    ],
  },

  // ─── Generate ─────────────────────────────────────────────────────────────
  {
    slug: "lorem-ipsum",
    name: "Lorem Ipsum Generator",
    description: "Generate placeholder text for your designs",
    icon: "FileText",
    category: "Generate",
    keywords: [
      "lorem ipsum generator", "lorem ipsum", "placeholder text generator",
      "dummy text generator", "lorem ipsum online", "generate lorem ipsum",
      "random text generator", "filler text generator",
      "lorem ipsum paragraph generator", "dummy content generator",
      "placeholder content", "lorem ipsum words generator",
    ],
  },
  {
    slug: "password-generator",
    name: "Password Generator",
    description: "Generate strong, random passwords with custom rules",
    icon: "ShieldCheck",
    category: "Generate",
    keywords: [
      "password generator", "random password generator", "strong password generator",
      "secure password generator", "password generator online",
      "generate password", "complex password generator",
      "random password online", "password creator", "password maker",
      "strong random password", "secure random password generator",
    ],
  },
  {
    slug: "uuid-generator",
    name: "UUID Generator",
    description: "Generate RFC 4122 v4 UUIDs in bulk",
    icon: "Hash",
    category: "Generate",
    keywords: [
      "uuid generator", "uuid generator online", "generate uuid",
      "guid generator", "uuid v4 generator", "random uuid generator",
      "unique id generator", "uuid creator", "generate guid online",
      "uuid4 generator", "universally unique identifier generator",
      "random guid", "uuid generator free",
    ],
  },
  {
    slug: "json-to-typescript",
    name: "JSON to TypeScript",
    description: "Auto-generate TypeScript interfaces from JSON objects",
    icon: "Code2",
    category: "Generate",
    keywords: [
      "json to typescript", "json to typescript interface", "json to ts",
      "convert json to typescript", "json typescript generator",
      "json to interface typescript", "generate typescript from json",
      "json to type typescript", "json schema to typescript",
      "json to ts types", "typescript interface generator from json",
    ],
  },
  {
    slug: "qr-code-generator",
    name: "QR Code Generator",
    description: "Generate QR codes from any URL or text",
    icon: "QrCode",
    category: "Generate",
    keywords: [
      "qr code generator", "qr code generator online", "generate qr code",
      "free qr code generator", "qr code maker", "qr code creator",
      "create qr code online", "qr code for url", "qr code for text",
      "custom qr code generator", "qr code generator free no signup",
    ],
  },
  {
    slug: "jwt-generator",
    name: "JWT Generator",
    description: "Create and sign JWTs with custom claims in-browser",
    icon: "FileLock2",
    category: "Generate",
    keywords: [
      "jwt generator", "jwt token generator", "generate jwt token",
      "create jwt online", "jwt creator", "json web token generator",
      "jwt sign online", "jwt builder", "generate jwt online",
      "jwt token creator", "hmac jwt generator", "jwt generator online free",
    ],
  },
  {
    slug: "git-command-generator",
    name: "Git Command Generator",
    description: "Find and copy git commands fast — search, filter by category, with warnings",
    icon: "GitBranch",
    category: "Generate",
    keywords: [
      "git command generator", "git commands", "git cheat sheet",
      "git command helper", "git undo commit", "git reset command",
      "git branch commands", "git stash command", "git rebase command",
      "git commands list", "git command lookup", "git help online",
      "how to undo git commit", "git command finder",
    ],
  },
  {
    slug: "markdown-table-generator",
    name: "Markdown Table Generator",
    description: "Build Markdown tables visually — edit cells, align columns, export as HTML",
    icon: "Table",
    category: "Generate",
    keywords: [
      "markdown table generator", "markdown table", "generate markdown table",
      "markdown table creator", "markdown table builder online",
      "table to markdown", "markdown table formatter",
      "create markdown table online", "markdown table editor",
      "github markdown table", "markdown table syntax generator",
    ],
  },
  {
    slug: "meta-tags-generator",
    name: "Meta Tags Generator",
    description: "Generate Open Graph, Twitter Card, and SEO meta tags with live previews",
    icon: "Tags",
    category: "Generate",
    keywords: [
      "meta tags generator", "og tags generator", "open graph generator",
      "seo meta tags generator", "twitter card generator",
      "meta description generator", "open graph meta tags",
      "og image meta tag", "meta tag creator", "social media meta tags",
      "meta tags seo online", "generate meta tags free",
      "og tags preview", "social share preview tool",
    ],
  },

  // ─── Convert ──────────────────────────────────────────────────────────────
  {
    slug: "color-converter",
    name: "Color Converter",
    description: "Convert between HEX, RGB, and HSL color formats",
    icon: "Palette",
    category: "Convert",
    keywords: [
      "color converter", "hex to rgb", "rgb to hex", "hex to hsl",
      "hsl to hex", "color code converter", "hex color converter",
      "rgb to hsl converter", "color picker online", "hex color picker",
      "css color converter", "color format converter",
      "hex to rgba", "color code translator",
    ],
  },
  {
    slug: "timestamp-converter",
    name: "Timestamp Converter",
    description: "Convert Unix timestamps to human-readable dates",
    icon: "Clock",
    category: "Convert",
    keywords: [
      "timestamp converter", "unix timestamp converter", "epoch converter",
      "unix time converter", "timestamp to date", "date to timestamp",
      "epoch to date", "unix epoch converter", "convert timestamp online",
      "epoch time converter", "unix timestamp to human readable",
      "milliseconds to date", "epoch timestamp converter",
    ],
  },
  {
    slug: "number-base-converter",
    name: "Number Base Converter",
    description: "Convert numbers between binary, octal, decimal, and hex",
    icon: "Calculator",
    category: "Convert",
    keywords: [
      "number base converter", "binary to decimal", "decimal to binary",
      "hex to decimal", "decimal to hex", "binary converter online",
      "hexadecimal converter", "octal converter", "base converter online",
      "number system converter", "binary decimal hex converter",
      "decimal to octal", "hex to binary converter",
    ],
  },
  {
    slug: "string-case-converter",
    name: "String Case Converter",
    description: "Convert text between camelCase, snake_case, kebab-case and more",
    icon: "CaseSensitive",
    category: "Convert",
    keywords: [
      "string case converter", "camelcase converter", "snake_case converter",
      "kebab case converter", "camel case to snake case",
      "snake case to camel case", "uppercase lowercase converter",
      "text case converter", "pascal case converter",
      "string case changer", "case converter online", "title case converter",
    ],
  },
  {
    slug: "json-yaml",
    name: "JSON ↔ YAML Converter",
    description: "Convert between JSON and YAML formats instantly",
    icon: "ArrowLeftRight",
    category: "Convert",
    keywords: [
      "json to yaml", "yaml to json", "json yaml converter",
      "convert json to yaml", "convert yaml to json",
      "yaml json online", "json yaml online converter",
      "yaml formatter", "yaml validator online", "json to yaml online",
      "yaml to json converter online", "yaml json transform",
    ],
  },
  {
    slug: "cidr-calculator",
    name: "IP / CIDR Calculator",
    description: "Calculate subnet masks, IP ranges, and host counts from CIDR notation",
    icon: "Network",
    category: "Convert",
    keywords: [
      "cidr calculator", "subnet calculator", "ip subnet calculator",
      "cidr notation calculator", "subnet mask calculator",
      "ip cidr calculator online", "network calculator",
      "subnet range calculator", "ip range calculator",
      "cidr to ip range", "subnet calculator online free",
      "ipv4 subnet calculator", "network address calculator",
      "cidr block calculator",
    ],
  },

  {
    slug: "docker-run-to-compose",
    name: "Docker Run to Compose",
    description: "Convert docker run commands to docker-compose.yml and back",
    icon: "Container",
    category: "Convert",
    keywords: [
      "docker run to compose", "docker run to docker-compose", "docker compose converter",
      "docker run converter", "docker to compose yaml", "docker compose generator",
      "convert docker run command", "docker-compose.yml generator", "docker run parser",
      "docker compose online", "docker compose tool", "docker run to yaml",
      "docker compose best practices", "docker run translator",
    ],
  },

  // ─── Test ─────────────────────────────────────────────────────────────────
  {
    slug: "regex-tester",
    name: "Regex Tester",
    description: "Test and debug regular expressions with live highlighting",
    icon: "SearchCode",
    category: "Test",
    keywords: [
      "regex tester", "regex tester online", "regular expression tester",
      "regex checker", "regex debugger", "test regex online",
      "regex validator", "regex matcher online", "javascript regex tester",
      "regex pattern tester", "regex live tester", "regex101 alternative",
      "regular expression checker online", "regex evaluator",
    ],
  },
  {
    slug: "diff-checker",
    name: "Diff Checker",
    description: "Compare two texts and highlight differences",
    icon: "GitCompare",
    category: "Test",
    keywords: [
      "diff checker", "diff checker online", "text diff tool",
      "compare two texts online", "text comparison tool",
      "diff tool online", "code diff checker", "file diff online",
      "compare text online", "diff viewer online",
      "line diff checker", "text diff comparison online",
    ],
  },
  {
    slug: "cron-tester",
    name: "CRON Expression Tester",
    description: "Parse cron expressions and preview upcoming run times",
    icon: "Timer",
    category: "Test",
    keywords: [
      "cron expression tester", "cron tester online", "cron parser",
      "cron job tester", "cron expression parser", "cron validator",
      "cron schedule tester", "cron expression builder",
      "test cron expression", "cron syntax checker",
      "cron expression explainer", "quartz cron tester",
    ],
  },
  {
    slug: "http-request",
    name: "HTTP Request Builder",
    description: "Build and send HTTP requests like a lightweight Postman",
    icon: "Send",
    category: "Test",
    keywords: [
      "http request builder", "api tester online", "rest api tester",
      "http client online", "api testing tool", "http tester online",
      "postman alternative online", "rest client online",
      "http request tester", "api request builder",
      "test api online", "http get post tester",
    ],
  },
  {
    slug: "config-validator",
    name: "YAML / TOML / JSON Validator",
    description: "Validate and convert between YAML, TOML, and JSON formats",
    icon: "CheckCheck",
    category: "Test",
    keywords: [
      "yaml validator", "toml validator", "json validator online",
      "yaml linter online", "config file validator", "yaml syntax checker",
      "validate yaml online", "toml parser online", "yaml json toml converter",
      "yaml format validator", "config validator online",
    ],
  },
  {
    slug: "text-diff",
    name: "Text Diff",
    description: "Inline character-level diff between two short texts",
    icon: "Diff",
    category: "Test",
    keywords: [
      "text diff", "character diff", "word diff online",
      "inline diff tool", "text compare online", "diff text online",
      "character level diff", "word level diff", "text difference checker",
      "compare strings online", "string diff tool", "text diff viewer",
    ],
  },
  {
    slug: "xpath-tester",
    name: "XPath Tester",
    description: "Test XPath expressions against XML and HTML with live results",
    icon: "Code2",
    category: "Test",
    keywords: [
      "xpath tester", "xpath tester online", "xpath evaluator",
      "xpath query tester", "test xpath expression", "xpath online",
      "xpath tool", "xml xpath tester", "html xpath tester",
      "xpath checker", "xpath validator", "xpath expression tester",
      "xpath browser", "xpath selector tester", "xpath debugger",
    ],
  },

  // ─── Design ───────────────────────────────────────────────────────────────
  {
    slug: "css-animations",
    name: "CSS Animations",
    description: "Copy-paste HTML+CSS animation combos with live previews",
    icon: "Sparkles",
    category: "Design",
    keywords: [
      "css animations", "css animation examples", "css animation code",
      "css animation library", "copy paste css animations",
      "css button animation", "css loader animation", "css hover effects",
      "css keyframe animations", "css animation generator",
      "css animation snippets", "css transition effects",
      "pure css animations", "css animation collection",
    ],
  },
  {
    slug: "css-gradient",
    name: "CSS Gradient Generator",
    description: "Build linear, radial, and conic CSS gradients visually",
    icon: "Layers",
    category: "Design",
    keywords: [
      "css gradient generator", "gradient generator online",
      "linear gradient generator", "radial gradient generator",
      "css background gradient", "gradient color picker",
      "gradient maker online", "css gradient maker",
      "gradient css code generator", "mesh gradient generator",
      "conic gradient generator", "gradient generator free",
    ],
  },
  {
    slug: "color-palette",
    name: "Color Palette Generator",
    description: "Generate harmonious color palettes from any base color",
    icon: "PaintBucket",
    category: "Design",
    keywords: [
      "color palette generator", "color scheme generator",
      "color palette online", "color combination generator",
      "complementary color generator", "analogous color generator",
      "color palette creator", "color scheme creator online",
      "triadic color generator", "color harmony generator",
      "web color palette generator", "brand color palette generator",
    ],
  },

  // ─── Security ─────────────────────────────────────────────────────────────
  {
    slug: "crypto-tools",
    name: "AES / RSA Encryption",
    description: "Encrypt and decrypt text using AES-GCM and RSA-OAEP",
    icon: "Shield",
    category: "Security",
    keywords: [
      "aes encryption online", "rsa encryption online",
      "encrypt text online", "decrypt text online",
      "aes encryption tool", "browser encryption tool",
      "client side encryption", "aes gcm encryption online",
      "rsa encrypt decrypt online", "encrypt decrypt text browser",
      "aes 256 encryption online", "secure encryption tool free",
      "encrypt without uploading", "private encryption tool",
    ],
  },

  // ─── Reference ────────────────────────────────────────────────────────────
  {
    slug: "http-status-codes",
    name: "HTTP Status Codes",
    description: "Searchable reference for all HTTP status codes",
    icon: "Globe",
    category: "Reference",
    keywords: [
      "http status codes", "http status code list", "http error codes",
      "rest api status codes", "404 meaning", "500 error code",
      "http response codes", "http codes reference",
      "http status code reference", "list of http codes",
      "http 200 301 404 500", "http status code lookup",
      "what is http 403", "http codes cheat sheet",
    ],
  },
  {
    slug: "chmod-calculator",
    name: "Chmod Calculator",
    description: "Calculate Unix file permissions with visual checkboxes",
    icon: "Lock",
    category: "Reference",
    keywords: [
      "chmod calculator", "chmod calculator online", "linux permission calculator",
      "file permission calculator", "chmod 755", "chmod 777",
      "rwxr-xr-x meaning", "linux file permissions calculator",
      "octal permission calculator", "chmod converter",
      "unix permission calculator", "chmod number calculator",
      "linux chmod online", "rwx permissions calculator",
      "chmod 644 meaning", "symbolic permission calculator",
    ],
  },
  {
    slug: "unicode-explorer",
    name: "Unicode Explorer",
    description: "Search and inspect Unicode characters by name, code point, or symbol",
    icon: "Type",
    category: "Reference",
    keywords: [
      "unicode explorer", "unicode character lookup", "unicode table online",
      "unicode code point lookup", "unicode search online",
      "unicode character finder", "utf-8 character table",
      "unicode to html entity", "find unicode character",
      "unicode browser online", "unicode character search",
      "special characters unicode lookup", "unicode symbol finder",
    ],
  },
];

export const categories = ["Format", "Encode", "Generate", "Convert", "Test", "Design", "Security", "Reference"] as const;

export type Category = (typeof categories)[number];
