export interface Tool {
  slug: string;
  name: string;
  description: string;
  icon: string;
  category: string;
  keywords: string[];
}

export const tools: Tool[] = [
  {
    slug: "json-formatter",
    name: "JSON Formatter",
    description: "Format, validate and minify JSON instantly",
    icon: "Braces",
    category: "Format",
    keywords: ["json", "formatter", "validator", "beautifier", "minify"],
  },
  {
    slug: "base64",
    name: "Base64 Encoder/Decoder",
    description: "Encode or decode Base64 strings instantly",
    icon: "Binary",
    category: "Encode",
    keywords: ["base64", "encode", "decode", "encoder", "decoder"],
  },
  {
    slug: "url-encoder",
    name: "URL Encoder/Decoder",
    description: "Encode and decode URLs and query parameters",
    icon: "Link",
    category: "Encode",
    keywords: ["url", "encode", "decode", "percent-encoding", "uri"],
  },
  {
    slug: "regex-tester",
    name: "Regex Tester",
    description: "Test and debug regular expressions with live highlighting",
    icon: "SearchCode",
    category: "Test",
    keywords: ["regex", "regexp", "regular expression", "pattern", "match"],
  },
  {
    slug: "color-converter",
    name: "Color Converter",
    description: "Convert between HEX, RGB, and HSL color formats",
    icon: "Palette",
    category: "Convert",
    keywords: ["color", "hex", "rgb", "hsl", "converter", "picker"],
  },
  {
    slug: "lorem-ipsum",
    name: "Lorem Ipsum Generator",
    description: "Generate placeholder text for your designs",
    icon: "FileText",
    category: "Generate",
    keywords: ["lorem", "ipsum", "placeholder", "text", "dummy"],
  },
  {
    slug: "jwt-decoder",
    name: "JWT Decoder",
    description: "Decode and inspect JWT tokens instantly",
    icon: "KeyRound",
    category: "Encode",
    keywords: ["jwt", "token", "decode", "header", "payload", "json web token"],
  },
  {
    slug: "markdown-preview",
    name: "Markdown Preview",
    description: "Write and preview Markdown in real time",
    icon: "BookOpen",
    category: "Format",
    keywords: ["markdown", "md", "preview", "render", "html"],
  },
  {
    slug: "timestamp-converter",
    name: "Timestamp Converter",
    description: "Convert Unix timestamps to human-readable dates",
    icon: "Clock",
    category: "Convert",
    keywords: ["timestamp", "unix", "epoch", "date", "time", "convert"],
  },
  {
    slug: "password-generator",
    name: "Password Generator",
    description: "Generate strong, random passwords with custom rules",
    icon: "ShieldCheck",
    category: "Generate",
    keywords: ["password", "generator", "random", "secure", "strong"],
  },
  {
    slug: "uuid-generator",
    name: "UUID Generator",
    description: "Generate RFC 4122 v4 UUIDs in bulk",
    icon: "Hash",
    category: "Generate",
    keywords: ["uuid", "guid", "v4", "unique", "identifier", "random"],
  },
  {
    slug: "diff-checker",
    name: "Diff Checker",
    description: "Compare two texts and highlight differences",
    icon: "GitCompare",
    category: "Test",
    keywords: ["diff", "compare", "difference", "text", "code review"],
  },
  {
    slug: "css-animations",
    name: "CSS Animations",
    description: "Copy-paste HTML+CSS animation combos with live previews",
    icon: "Sparkles",
    category: "Design",
    keywords: ["css", "animation", "keyframes", "transition", "effects", "ui"],
  },
  // New tools
  {
    slug: "hash-generator",
    name: "Hash Generator",
    description: "Generate SHA-1, SHA-256, SHA-384 and SHA-512 hashes",
    icon: "Fingerprint",
    category: "Encode",
    keywords: ["hash", "sha", "sha256", "sha512", "sha1", "checksum", "digest", "crypto"],
  },
  {
    slug: "number-base-converter",
    name: "Number Base Converter",
    description: "Convert numbers between binary, octal, decimal, and hex",
    icon: "Calculator",
    category: "Convert",
    keywords: ["binary", "octal", "decimal", "hex", "hexadecimal", "base", "convert", "number"],
  },
  {
    slug: "string-case-converter",
    name: "String Case Converter",
    description: "Convert text between camelCase, snake_case, kebab-case and more",
    icon: "CaseSensitive",
    category: "Convert",
    keywords: ["camelcase", "snake_case", "kebab-case", "pascal", "uppercase", "lowercase", "case", "string"],
  },
  {
    slug: "json-to-typescript",
    name: "JSON to TypeScript",
    description: "Auto-generate TypeScript interfaces from JSON objects",
    icon: "Code2",
    category: "Generate",
    keywords: ["json", "typescript", "interface", "type", "generate", "schema"],
  },
  {
    slug: "json-yaml",
    name: "JSON ↔ YAML Converter",
    description: "Convert between JSON and YAML formats instantly",
    icon: "ArrowLeftRight",
    category: "Convert",
    keywords: ["json", "yaml", "yml", "convert", "transform", "format"],
  },
  {
    slug: "qr-code-generator",
    name: "QR Code Generator",
    description: "Generate QR codes from any URL or text",
    icon: "QrCode",
    category: "Generate",
    keywords: ["qr", "qrcode", "barcode", "scan", "url", "generate"],
  },
  {
    slug: "html-entity",
    name: "HTML Entity Encoder",
    description: "Encode and decode HTML entities and special characters",
    icon: "FileCode",
    category: "Encode",
    keywords: ["html", "entity", "encode", "decode", "escape", "unescape", "ampersand", "special characters"],
  },
  {
    slug: "cron-tester",
    name: "CRON Expression Tester",
    description: "Parse cron expressions and preview upcoming run times",
    icon: "Timer",
    category: "Test",
    keywords: ["cron", "crontab", "schedule", "expression", "job", "timer"],
  },
  {
    slug: "http-status-codes",
    name: "HTTP Status Codes",
    description: "Searchable reference for all HTTP status codes",
    icon: "Globe",
    category: "Reference",
    keywords: ["http", "status", "code", "404", "200", "500", "redirect", "error", "response"],
  },
  {
    slug: "chmod-calculator",
    name: "Chmod Calculator",
    description: "Calculate Unix file permissions with visual checkboxes",
    icon: "Lock",
    category: "Reference",
    keywords: ["chmod", "permissions", "unix", "linux", "rwx", "octal", "file"],
  },
  {
    slug: "css-gradient",
    name: "CSS Gradient Generator",
    description: "Build linear, radial, and conic CSS gradients visually",
    icon: "Layers",
    category: "Design",
    keywords: ["css", "gradient", "linear", "radial", "conic", "color", "background"],
  },
  {
    slug: "image-to-base64",
    name: "Image to Base64",
    description: "Convert images to Base64 data URIs for embedding",
    icon: "ImageIcon",
    category: "Encode",
    keywords: ["image", "base64", "data uri", "embed", "convert", "png", "jpg", "svg"],
  },
  {
    slug: "sql-formatter",
    name: "SQL Formatter",
    description: "Format and beautify SQL queries with dialect support",
    icon: "Database",
    category: "Format",
    keywords: ["sql", "formatter", "query", "mysql", "postgresql", "sqlite", "beautify", "indent"],
  },
  {
    slug: "color-palette",
    name: "Color Palette Generator",
    description: "Generate harmonious color palettes from any base color",
    icon: "PaintBucket",
    category: "Design",
    keywords: ["color", "palette", "complementary", "triadic", "analogous", "harmony", "generator", "hex", "hsl"],
  },
  {
    slug: "jwt-generator",
    name: "JWT Generator",
    description: "Create and sign JWTs with custom claims in-browser",
    icon: "FileLock2",
    category: "Generate",
    keywords: ["jwt", "json web token", "sign", "hs256", "hmac", "generate", "claims", "token"],
  },
  {
    slug: "crypto-tools",
    name: "AES / RSA Encryption",
    description: "Encrypt and decrypt text using AES-GCM and RSA-OAEP",
    icon: "Shield",
    category: "Security",
    keywords: ["aes", "rsa", "encryption", "decryption", "aes-gcm", "rsa-oaep", "crypto", "secure", "cipher"],
  },
  {
    slug: "http-request",
    name: "HTTP Request Builder",
    description: "Build and send HTTP requests like a lightweight Postman",
    icon: "Send",
    category: "Test",
    keywords: ["http", "request", "get", "post", "put", "delete", "api", "rest", "headers", "postman"],
  },
  {
    slug: "html-formatter",
    name: "HTML Formatter",
    description: "Prettify and minify HTML markup instantly",
    icon: "FileCode2",
    category: "Format",
    keywords: ["html", "formatter", "prettify", "minify", "beautify", "indent", "markup"],
  },
  {
    slug: "config-validator",
    name: "YAML / TOML / JSON Validator",
    description: "Validate and convert between YAML, TOML, and JSON formats",
    icon: "CheckCheck",
    category: "Test",
    keywords: ["yaml", "toml", "json", "validate", "validator", "lint", "config", "convert"],
  },
  {
    slug: "text-diff",
    name: "Text Diff",
    description: "Inline character-level diff between two short texts",
    icon: "Diff",
    category: "Test",
    keywords: ["diff", "text", "compare", "character", "inline", "difference", "change"],
  },
  {
    slug: "cidr-calculator",
    name: "IP / CIDR Calculator",
    description: "Calculate subnet masks, IP ranges, and host counts from CIDR notation",
    icon: "Network",
    category: "Convert",
    keywords: ["ip", "cidr", "subnet", "mask", "network", "broadcast", "calculator", "ipv4"],
  },
  {
    slug: "unicode-explorer",
    name: "Unicode Explorer",
    description: "Search and inspect Unicode characters by name, code point, or symbol",
    icon: "Type",
    category: "Reference",
    keywords: ["unicode", "character", "code point", "utf8", "utf16", "symbol", "emoji", "explorer"],
  },
];

export const categories = ["Format", "Encode", "Generate", "Convert", "Test", "Design", "Security", "Reference"] as const;

export type Category = (typeof categories)[number];
